***Keywords***

Close Banner
    home_page.Close First Banner

Verify URL
    home_page.Verify URL

Verify Input Search
    home_page.Verify Input Search

Verify Detail of Index Page
    home_page.Verify Detail of Index Page

Input Search dior
    home_page.Input Search dior

# Verify Page After Search dior
#     home_page.Verify Page After Search dior

# Choose Product La Mousse
#     home_page.Choose Product La Mousse

